use flatpak_rs::source::FlatpakSource;

pub const CRATES_IO_URL: &str = "https://static.crates.io/crates";

pub struct CargoLock {
    pub version: String,

    pub package: Vec<CargoLock>,
}

pub struct CargoLockPackage {
    pub name: String,
    pub source: String,
    pub checksum: String,
    pub version: String,
    pub dependencies: Vec<String>,
}

pub fn get_sources(manifest_path: &str) -> Vec<FlatpakSource> {
    vec![]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore]
    pub fn test_get_sources() {
        let cargo_lock_manifest: &str = r###"
            # This file is automatically @generated by Cargo.
            # It is not intended for manual editing.
            version = 3

            [[package]]
            name = "aho-corasick"
            version = "0.7.18"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "1e37cfd5e7657ada45f742d6e99ca5788580b5c529dc78faf11ece6dc702656f"
            dependencies = [
            "memchr",
            ]

            [[package]]
            name = "atty"
            version = "0.2.14"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "d9b39be18770d11421cdb1b9947a45dd3f37e93092cbf377614828a319d5fee8"
            dependencies = [
            "hermit-abi",
            "libc",
            "winapi",
            ]

            [[package]]
            name = "autocfg"
            version = "1.1.0"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "d468802bab17cbc0cc575e9b053f41e72aa36bfa6b7f55e3529ffa43161b97fa"

            [[package]]
            name = "bitflags"
            version = "1.3.2"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "bef38d45163c2f1dde094a7dfd33ccf595c92905c8f8f4fdc18d06fb1037718a"

            [[package]]
            name = "cfg-if"
            version = "1.0.0"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
        "###;
        let sources = get_sources(cargo_lock_manifest);

        assert_eq!(sources.len(), 5);
    }
}
